# Generated by Django 2.2 on 2020-02-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='age_analysis',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='alert_message',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='alias_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
