# Generated by Django 2.2 on 2020-02-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0002_auto_20200220_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='Date_Uploaded',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='Date_Discovered',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='age_analysis',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
