# Generated by Django 2.2 on 2020-03-08 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0003_auto_20200225_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='OPERATORS_RESPONSE',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='Summary_Of_Incidence_and_CAMT_observation_during_Investigation',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
