# Generated by Django 2.2 on 2020-03-09 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0004_auto_20200308_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='statusCheck',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Closed', 'Closed')], default='', max_length=20, null=True),
        ),
    ]
