# Generated by Django 2.2 on 2020-03-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0005_auto_20200309_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='role',
            field=models.CharField(blank=True, choices=[('Branch', 'Branch')], default='', max_length=200, null=True),
        ),
    ]
