# Generated by Django 2.2 on 2020-04-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0006_alert_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='role',
            field=models.CharField(blank=True, choices=[('Branch', 'Branch'), ('camt', 'camt')], default='', max_length=200, null=True),
        ),
    ]
